# Configuración de la aplicación en Fly.io
app = "jfk-fe-mongodb"
primary_region = "mia"

# Configuración del entorno
[env]
  MONGO_INITDB_ROOT_USERNAME = "admin"
  MONGO_INITDB_ROOT_PASSWORD = "rH5;v*7(89^1]£(8c"

# Configuración de los servicios y puertos
[http_service]
  http_checks = []
  internal_port = 27017
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["db"]

# Configuración de la imagen Docker y el comando de inicio
[experimental]
private_network = true
cmd = ["mongod", "--ipv6"]

[processes]
db = "docker-entrypoint.sh mongod"

[mounts]
  destination = "/data/db"
  source = "mongo_volume"
